version: '3'

services:
  php:
    volumes:
      - php:/srv/app

  nginx:
    volumes:
      - php:/srv/app

volumes:
  php:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    php:
      alpha: '.'
      beta: 'volume://php'
      mode: 'two-way-safe'
      ignore:
        paths:
          - '.idea'
          - '.git'
          - '.github'
          - '.gitignore'
          - 'README.md'
